<a href="https://colab.research.google.com/github/bhomik179/experiment-10-/blob/main/Panda_exp10_sitpune_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bhomik Keshi
# Prn **25070123172**

# Experiement number **10**

# Study of pandas library

In [104]:
# Introduction to Pandas Library

"""
Pandas stands for "Panel Data".

It is a powerful Python library used for:

1. Working with structured data
2. (EDA)
3. Data cleaning and preprocessing
4. Data manipulation and transformation
"""

'\nPandas stands for "Panel Data".\n\nIt is a powerful Python library used for:\n\n1. Working with structured data\n2. Performing Exploratory Data Analysis (EDA)\n3. Data cleaning and preprocessing\n4. Data manipulation and transformation\n'

In [132]:
import pandas as pd

# -------------------------------
# Create a Series
# -------------------------------
print("Pandas Series:")
s = pd.Series([10, 20, 30, 40])
display(s)


# -------------------------------
# Create a DataFrame
# -------------------------------
print("\nDataFrame:")
data = {
    "Name": ["a", "b", "c"],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)
display(df)


print("\nShape of DataFrame (Rows, Columns):")
print(df.shape)

print("\nNumber of Dimensions:")
print(df.ndim)

print("\nTotal Number of Elements:")
print(df.size)

print("\nColumn Names:")
print(df.columns)

print("\nData Types of Each Column:")
print(df.dtypes)

print("\nRow and Column Axis Labels:")
print(df.axes)




print("\nData in 'Name' Column:")
display(df["Name"])

print("\nRow with index label 1:")
display(df.loc[1])

print("\nValue at row index 1 and column index 1:")
print(df.iloc[1, 1])



print("\nFirst 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

# Add a new column


'''If marks 80-90-First class
IF marks >=90-distinction
If marks >80-Second class'''

df["Grade"]=["First class","distinction","Second class"]
df
print()


# Change marks of student A to 88
df.iloc[0,1] = 81
df
print()

Pandas Series:

0    10
1    20
2    30
3    40
dtype: int64

DataFrame:

  Name  Marks
0    a     85
1    b     90
2    c     78

Shape of DataFrame (Rows, Columns):
(3, 2)

Number of Dimensions:
2

Total Number of Elements:
6

Column Names:
Index(['Name', 'Marks'], dtype='object')

Data Types of Each Column:
Name     object
Marks     int64
dtype: object

Row and Column Axis Labels:
[RangeIndex(start=0, stop=3, step=1), Index(['Name', 'Marks'], dtype='object')]

Data in 'Name' Column:

0    a
1    b
2    c
Name: Name, dtype: object

Row with index label 1:

Name      b
Marks    90
Name: 1, dtype: object

Value at row index 1 and column index 1:
90

First 5 Rows:

  Name  Marks
0    a     85
1    b     90
2    c     78

Last 5 Rows:

  Name  Marks
0    a     85
1    b     90
2    c     78

  Name  Marks         Grade
0    a     81   First class
1    b     90   distinction
2    c     78  Second class

In [131]:
# Update Data in DataFrame
# Change marks of student A to 88

df.loc[0,"Marks"] = 81
df
print()

  Name  Marks         Grade
0    a     81   First class
1    b     90   distinction
2    c     78  Second class

In [149]:
# Delete the 'Grade' column
df.drop("Grade", axis=1, inplace=True, errors='ignore')

df

  Name  Marks
0    a     81
1    b     90
2    c     78

In [151]:
# Perform Basic Statistical Analysis

mean1=df["Marks"].mean()
display(mean1)
print()

min1=df["Marks"].min()
display(min1)
print()

min1=df["Marks"].max()
display(min1)
print()



# perform basic Statistical Analysis

np.float64(83.0)

78

90

In [152]:
# apply condition (filtering)
# display student scoring more than 80

df[df["Marks"] > 80]

  Name  Marks
0    a     81
1    b     90